import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin, interval, startWith, switchMap } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { TwinService } from '../../core/services/twin.service';
import { VitalsService } from '../../core/services/vitals.service';
import { LabService } from '../../core/services/lab.service';
import { ConsentService } from '../../core/services/consent.service';
import { FhirService } from '../../core/services/fhir.service';
import { RiskService } from '../../core/services/risk.service';
import { PatientService } from '../../core/services/patient.service';
import { AlertService } from '../../core/services/alert.service';
import { CarePlan, CarePlanOutcome, Alert, Consent, HealthTwin, LabResult, PatientDetail, RiskPrediction, Vitals } from '../../core/models/api.models';
import { CarePlanService } from '../../core/services/care-plan.service';

@Component({ selector: 'app-patient-360', standalone: true, imports: [CommonModule, RouterLink], templateUrl: './patient-360.component.html', styleUrl: './patient-360.component.scss' })
export class Patient360Component {
  private readonly route = inject(ActivatedRoute); private readonly destroyRef = inject(DestroyRef); private readonly patientsApi = inject(PatientService); private readonly twinApi = inject(TwinService); private readonly vitalsApi = inject(VitalsService); private readonly labApi = inject(LabService); private readonly consentApi = inject(ConsentService); private readonly fhirApi = inject(FhirService); private readonly riskApi = inject(RiskService); private readonly alertsApi = inject(AlertService); private readonly carePlanApi = inject(CarePlanService);
  readonly loading = signal(true); readonly error = signal(''); readonly patient = signal<PatientDetail | null>(null); readonly twin = signal<HealthTwin | null>(null); readonly vitals = signal<Vitals[]>([]); readonly labs = signal<LabResult[]>([]); readonly consents = signal<Consent[]>([]); readonly fhirResources = signal<import('../../core/models/api.models').FhirResource[]>([]); readonly cardiovascularRisk = signal<RiskPrediction | null>(null); readonly diabetesRisk = signal<RiskPrediction | null>(null); readonly cardiovascularRiskError = signal(''); readonly diabetesRiskError = signal(''); readonly riskHistory = signal<RiskPrediction[]>([]); readonly riskHistoryLoading = signal(true); readonly riskHistoryError = signal(''); readonly riskLoading = signal(''); readonly riskError = signal(''); readonly activeAlerts = signal<Alert[]>([]); readonly alertHistory = signal<Alert[]>([]); readonly alertLoading = signal(true); readonly alertError = signal(''); readonly alertAction = signal(''); readonly carePlan = signal<CarePlan | null>(null); readonly carePlanLoading = signal(true); readonly carePlanError = signal(''); readonly carePlanAction = signal(''); readonly outcomes = signal<CarePlanOutcome[]>([]);
  constructor() { this.load(this.route.snapshot.paramMap.get('patientId') ?? ''); }
  load(id: string): void { this.loading.set(true); forkJoin({ patient: this.patientsApi.get(id), twin: this.twinApi.get(id), completeness: this.twinApi.completeness(id), vitals: this.vitalsApi.list(id), labs: this.labApi.list(id), fhir: this.fhirApi.list(id), consents: this.consentApi.list(id) }).subscribe({ next: data => { this.patient.set(data.patient); this.twin.set({ ...data.twin, completenessPercentage: data.completeness.completenessPercentage, missingDataPoints: data.completeness.missingDataPoints }); this.vitals.set(data.vitals.content); this.labs.set(data.labs.content); this.fhirResources.set(data.fhir.content); this.consents.set(data.consents); this.loading.set(false); this.loadRiskData(id); this.startAlertPolling(id); this.loadCarePlan(id); }, error: () => { this.error.set('This patient record could not be loaded.'); this.loading.set(false); } }); }
  loadCarePlan(patientId: string): void { this.carePlanLoading.set(true); this.carePlanApi.active(patientId).subscribe({ next: plan => { this.carePlan.set(plan); this.carePlanLoading.set(false); this.carePlanError.set(''); this.loadOutcomes(plan.id); }, error: response => { this.carePlan.set(null); this.carePlanLoading.set(false); this.carePlanError.set(response.status === 404 ? '' : 'Care-plan information could not be loaded.'); } }); }
  generateCarePlan(): void { const patientId = this.patient()?.id; if (!patientId) return; this.carePlanAction.set('generate'); this.carePlanApi.generate(patientId).subscribe({ next: plan => { this.carePlan.set(plan); this.carePlanAction.set(''); this.loadOutcomes(plan.id); }, error: () => { this.carePlanAction.set(''); this.carePlanError.set('The care plan could not be generated.'); } }); }
  transitionCarePlan(action: 'activate' | 'pause' | 'complete' | 'cancel'): void { const plan = this.carePlan(); if (!plan) return; this.carePlanAction.set(action); this.carePlanApi.transition(plan.id, action).subscribe({ next: updated => { this.carePlan.set(updated); this.carePlanAction.set(''); }, error: response => { this.carePlanAction.set(''); this.carePlanError.set(response.status === 409 ? 'That care-plan status change is not allowed.' : 'The care plan could not be updated.'); } }); }
  markIntervention(interventionId: string, action: 'complete' | 'miss'): void { const plan = this.carePlan(); if (!plan) return; this.carePlanAction.set(interventionId); this.carePlanApi.mark(plan.id, interventionId, action).subscribe({ next: updated => { this.carePlan.set(updated); this.carePlanAction.set(''); }, error: () => { this.carePlanAction.set(''); this.carePlanError.set('The intervention could not be updated.'); } }); }
  loadOutcomes(planId: string): void { this.carePlanApi.outcomes(planId).subscribe({ next: outcomes => this.outcomes.set(outcomes), error: () => this.outcomes.set([]) }); }
  startAlertPolling(patientId: string): void { interval(10000).pipe(startWith(0), switchMap(() => forkJoin({ active: this.alertsApi.active(patientId), history: this.alertsApi.history(patientId) })), takeUntilDestroyed(this.destroyRef)).subscribe({ next: data => { this.activeAlerts.set(data.active.content); this.alertHistory.set(data.history.content); this.alertLoading.set(false); this.alertError.set(''); }, error: () => { this.alertLoading.set(false); this.alertError.set('Alerts could not be loaded.'); } }); }
  acknowledge(alert: Alert): void { this.alertAction.set(alert.id); this.alertsApi.acknowledge(alert.id).subscribe({ next: () => { this.alertAction.set(''); this.loadAlertsOnce(alert.patientId); }, error: () => { this.alertAction.set(''); this.alertError.set('The alert could not be acknowledged.'); } }); }
  resolve(alert: Alert): void { this.alertAction.set(alert.id); this.alertsApi.resolve(alert.id).subscribe({ next: () => { this.alertAction.set(''); this.loadAlertsOnce(alert.patientId); }, error: () => { this.alertAction.set(''); this.alertError.set('The alert could not be resolved.'); } }); }
  private loadAlertsOnce(patientId: string): void { forkJoin({ active: this.alertsApi.active(patientId), history: this.alertsApi.history(patientId) }).subscribe({ next: data => { this.activeAlerts.set(data.active.content); this.alertHistory.set(data.history.content); }, error: () => this.alertError.set('Alerts could not be loaded.') }); }
  loadRiskData(patientId: string): void { this.riskHistoryLoading.set(true); this.riskHistoryError.set(''); this.riskApi.latest(patientId, 'CARDIOVASCULAR').subscribe({ next: prediction => { this.cardiovascularRisk.set(prediction); this.cardiovascularRiskError.set(''); }, error: response => { this.cardiovascularRisk.set(null); this.cardiovascularRiskError.set(response.status === 404 ? '' : this.riskMessage(response)); } }); this.riskApi.latest(patientId, 'DIABETES').subscribe({ next: prediction => { this.diabetesRisk.set(prediction); this.diabetesRiskError.set(''); }, error: response => { this.diabetesRisk.set(null); this.diabetesRiskError.set(response.status === 404 ? '' : this.riskMessage(response)); } }); this.riskApi.history(patientId).subscribe({ next: history => { this.riskHistory.set(history.content); this.riskHistoryLoading.set(false); }, error: response => { this.riskHistory.set([]); this.riskHistoryLoading.set(false); this.riskHistoryError.set(this.riskMessage(response)); } }); }
  predict(modelType: string): void { const patientId = this.patient()?.id; if (!patientId) return; this.riskLoading.set(modelType); this.riskError.set(''); this.riskApi.predict(patientId, modelType).subscribe({ next: prediction => { if (modelType === 'DIABETES') this.diabetesRisk.set(prediction); else this.cardiovascularRisk.set(prediction); this.riskLoading.set(''); this.loadRiskData(patientId); }, error: response => { this.riskLoading.set(''); this.riskError.set(this.riskMessage(response)); } }); }
  riskMessage(response: HttpErrorResponse): string { if (response.status === 403) return 'You are not authorized to view this risk information.'; if (response.status === 503) return 'The ML service is temporarily unavailable.'; if (response.status === 404) return 'No prediction has been recorded yet.'; return 'Risk information could not be loaded.'; }
  activeConsent(): Consent | undefined { return this.consents().find(consent => consent.status === 'GRANTED' && (!consent.expiresAt || new Date(consent.expiresAt) > new Date())); }
}
