import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { TwinService } from '../../core/services/twin.service';
import { VitalsService } from '../../core/services/vitals.service';
import { LabService } from '../../core/services/lab.service';
import { ConsentService } from '../../core/services/consent.service';
import { FhirService } from '../../core/services/fhir.service';
import { RiskService } from '../../core/services/risk.service';
import { PatientService } from '../../core/services/patient.service';
import { Consent, HealthTwin, LabResult, PatientDetail, RiskPrediction, Vitals } from '../../core/models/api.models';

@Component({ selector: 'app-patient-360', standalone: true, imports: [CommonModule, RouterLink], templateUrl: './patient-360.component.html', styleUrl: './patient-360.component.scss' })
export class Patient360Component {
  private readonly route = inject(ActivatedRoute); private readonly patientsApi = inject(PatientService); private readonly twinApi = inject(TwinService); private readonly vitalsApi = inject(VitalsService); private readonly labApi = inject(LabService); private readonly consentApi = inject(ConsentService); private readonly fhirApi = inject(FhirService); private readonly riskApi = inject(RiskService);
  readonly loading = signal(true); readonly error = signal(''); readonly patient = signal<PatientDetail | null>(null); readonly twin = signal<HealthTwin | null>(null); readonly vitals = signal<Vitals[]>([]); readonly labs = signal<LabResult[]>([]); readonly consents = signal<Consent[]>([]); readonly fhirResources = signal<import('../../core/models/api.models').FhirResource[]>([]); readonly cardiovascularRisk = signal<RiskPrediction | null>(null); readonly diabetesRisk = signal<RiskPrediction | null>(null); readonly cardiovascularRiskError = signal(''); readonly diabetesRiskError = signal(''); readonly riskHistory = signal<RiskPrediction[]>([]); readonly riskHistoryLoading = signal(true); readonly riskHistoryError = signal(''); readonly riskLoading = signal(''); readonly riskError = signal('');
  constructor() { this.load(this.route.snapshot.paramMap.get('patientId') ?? ''); }
  load(id: string): void { this.loading.set(true); forkJoin({ patient: this.patientsApi.get(id), twin: this.twinApi.get(id), completeness: this.twinApi.completeness(id), vitals: this.vitalsApi.list(id), labs: this.labApi.list(id), fhir: this.fhirApi.list(id), consents: this.consentApi.list(id) }).subscribe({ next: data => { this.patient.set(data.patient); this.twin.set({ ...data.twin, completenessPercentage: data.completeness.completenessPercentage, missingDataPoints: data.completeness.missingDataPoints }); this.vitals.set(data.vitals.content); this.labs.set(data.labs.content); this.fhirResources.set(data.fhir.content); this.consents.set(data.consents); this.loading.set(false); this.loadRiskData(id); }, error: () => { this.error.set('This patient record could not be loaded.'); this.loading.set(false); } }); }
  loadRiskData(patientId: string): void { this.riskHistoryLoading.set(true); this.riskHistoryError.set(''); this.riskApi.latest(patientId, 'CARDIOVASCULAR').subscribe({ next: prediction => { this.cardiovascularRisk.set(prediction); this.cardiovascularRiskError.set(''); }, error: response => { this.cardiovascularRisk.set(null); this.cardiovascularRiskError.set(response.status === 404 ? '' : this.riskMessage(response)); } }); this.riskApi.latest(patientId, 'DIABETES').subscribe({ next: prediction => { this.diabetesRisk.set(prediction); this.diabetesRiskError.set(''); }, error: response => { this.diabetesRisk.set(null); this.diabetesRiskError.set(response.status === 404 ? '' : this.riskMessage(response)); } }); this.riskApi.history(patientId).subscribe({ next: history => { this.riskHistory.set(history.content); this.riskHistoryLoading.set(false); }, error: response => { this.riskHistory.set([]); this.riskHistoryLoading.set(false); this.riskHistoryError.set(this.riskMessage(response)); } }); }
  predict(modelType: string): void { const patientId = this.patient()?.id; if (!patientId) return; this.riskLoading.set(modelType); this.riskError.set(''); this.riskApi.predict(patientId, modelType).subscribe({ next: prediction => { if (modelType === 'DIABETES') this.diabetesRisk.set(prediction); else this.cardiovascularRisk.set(prediction); this.riskLoading.set(''); this.loadRiskData(patientId); }, error: response => { this.riskLoading.set(''); this.riskError.set(this.riskMessage(response)); } }); }
  riskMessage(response: HttpErrorResponse): string { if (response.status === 403) return 'You are not authorized to view this risk information.'; if (response.status === 503) return 'The ML service is temporarily unavailable.'; if (response.status === 404) return 'No prediction has been recorded yet.'; return 'Risk information could not be loaded.'; }
  activeConsent(): Consent | undefined { return this.consents().find(consent => consent.status === 'GRANTED' && (!consent.expiresAt || new Date(consent.expiresAt) > new Date())); }
}
