server:
  port: 8080

spring:
  application:
    name: medisphere-backend
  
  mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/medisphere}
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: medisphere-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

medisphere:
  fhir:
    base-url: ${FHIR_BASE_URL:http://localhost:8081/fhir}
  
  wearable-simulator:
    enabled: false
    interval-ms: 5000
